# see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Raspberry Pi Tests

on: 
  workflow_dispatch:
  push:
    paths:
      - 'raspberry_pi/**'

jobs:
  build:

    runs-on: ubuntu-26.04
    
    defaults:
      run:
        working-directory: ./raspberry_pi

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14' 

      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pip install pytest-forked
      - run: pip install numpy
      - run: pip install robotpy
      - run: pip install robotpy-cscore
      - run: pip install robotpy-apriltag
      - run: pip install opencv-python
        
      - run: pytest --forked -vv -rA --full-trace tests/analysis
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/camera
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/config
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/dashboard
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/integration
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/interpreter
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/network
        if: ${{ always() }}
      - run: pytest --forked -vv -rA --full-trace tests/util
        if: ${{ always() }}
